function [radialStress, hoopStress, bulkStress, viscoelasticStretch] = ...
    computeStressesViscoManser(RMinusB, r, drdt, growthStretch, dgrowthStretchdt, mu, varsigma, params, dt, radialStressPrev)


    %% Compute the radial and hoop stresses including simple stress relaxation

    %% Elastic contribution to radial stress
    elasticIntegrand = 2 * growthStretch .* ...
        (r.^6 - growthStretch.^6 .* (RMinusB + params.B).^6) ./ r.^7;
    elasticIntegrand(1) = 0;  % avoid NaN at R=0

    %% Viscous contribution to radial stress
    viscoIntegrand = 12 * growthStretch.^2 .* ...
        ((growthStretch .* drdt - r .* dgrowthStretchdt) .* ...
        (RMinusB + params.B).^2 ./ r.^4);
    viscoIntegrand(1) = 0;

    %% Taylor expansion near R = 0
    growthStretchPrime       = gradient(growthStretch, RMinusB);
    growthStretchPrimePrime  = gradient(growthStretchPrime, RMinusB);
    dotgrowthStretchPrime    = gradient(dgrowthStretchdt, RMinusB);
    dotgrowthStretchPrimePrime = gradient(dotgrowthStretchPrime, RMinusB);

    approxElasticIntegrand = 2 * ( ...
        -3/2 * growthStretchPrime(1) / growthStretch(1) + ...
        (3/80 * (growthStretchPrime(1) / growthStretch(1))^2 ...
        - 6/5 * growthStretchPrimePrime(1) / growthStretch(1)) ...
        .* (RMinusB + params.B) );

    approxViscoIntegrand = -3 * ( ...
        ((growthStretch(1)^2) * dotgrowthStretchPrime(1) ...
        - growthStretch(1) * growthStretchPrime(1) * dgrowthStretchdt(1)) ...
        / growthStretch(1)^3 ...
        + (RMinusB + params.B) .* ...
        (13 * growthStretchPrime(1)^2 * dgrowthStretchdt(1) ...
        - 8 * growthStretch(1) * growthStretchPrimePrime(1) * dgrowthStretchdt(1) ...
        - 13 * growthStretch(1) * growthStretchPrime(1) * dotgrowthStretchPrime(1) ...
        + 8 * growthStretch(1)^2 * dotgrowthStretchPrimePrime(1)) ...
        / (10 * growthStretch(1)^3) );

    %% Composite integrands
    elasticIntegrandComposite = ...
        approxElasticIntegrand .* (RMinusB <= (params.radialStressIntegrandThreshold - params.B)) + ...
        elasticIntegrand .* (RMinusB >  (params.radialStressIntegrandThreshold - params.B));

    viscoIntegrandComposite = ...
        approxViscoIntegrand .* (RMinusB <= (params.radialStressIntegrandThreshold - params.B)) + ...
        viscoIntegrand .* (RMinusB >  (params.radialStressIntegrandThreshold - params.B));

    %% Integrate
    elasticIntegral = cumtrapz(RMinusB, elasticIntegrandComposite);
    viscoIntegral   = cumtrapz(RMinusB, viscoIntegrandComposite);

    %% Radial stress before relaxation
    radialStressKV = mu .* (elasticIntegral - elasticIntegral(end)) + ...
                     varsigma .* (viscoIntegral - viscoIntegral(end)) - ...
                     params.kappa * (r(end) - params.B) / params.B;

    %% Apply simple relaxation
    if isempty(radialStressPrev) || dt == 0
        radialStress = radialStressKV;
    else
        radialStress = radialStressKV - dt * radialStressPrev / params.tau;
    end
    

    %% Viscoelastic stretch
    viscoelasticStretch = r ./ ((RMinusB + params.B) .* growthStretch);
    viscoelasticStretch(1) = 1;

    approxViscoElasticStretch = 1 - (growthStretchPrime(1)/growthStretch(1)) .* (RMinusB + params.B)/4;
    viscoelasticStretch = approxViscoElasticStretch .* (RMinusB <= (params.elasticStretchIntegrandThreshold - params.B)) + ...
                          viscoelasticStretch .* (RMinusB > (params.elasticStretchIntegrandThreshold - params.B));

    %% Hoop and bulk stresses
    hoopStress = radialStress + mu .* (viscoelasticStretch.^2 - 1 ./ viscoelasticStretch.^4);
    bulkStress = radialStress + 2 * hoopStress;

end
