function [radialStress, hoopStress, bulkStress, viscoelasticStretch] = ...
    computeStressesViscoManser(RMinusB, r, drdt, growthStretch, dgrowthStretchdt, mu, varsigma, params)

%% Compute the radial and hoop stresses from the radial coordinates and
%% growth stretches at the material points in RMinusB.

    %% Elastic contribution to radial stress
    elasticIntegrand = 2 * growthStretch .* ...
        (r.^6 - growthStretch.^6 .* (RMinusB + params.B).^6) ./ r.^7;

    % Ignore the value at R = 0 (NaN)
    elasticIntegrand(1) = 0;

    %% Viscous contribution to radial stress
    viscoIntegrand = 12 * growthStretch.^2 .* ...
        ((growthStretch .* drdt - r .* dgrowthStretchdt) .* ...
        (RMinusB + params.B).^2 ./ r.^4);

    % Ignore the value at R = 0 (NaN)
    viscoIntegrand(1) = 0;

    %% Taylor expansion near R = 0
    growthStretchPrime       = gradient(growthStretch, RMinusB);
    growthStretchPrimePrime  = gradient(growthStretchPrime, RMinusB);
    dotgrowthStretchPrime    = gradient(dgrowthStretchdt, RMinusB);
    dotgrowthStretchPrimePrime = gradient(dotgrowthStretchPrime, RMinusB);

    %% Approximate elastic integrand near R = 0
    approxElasticIntegrand = 2 * ( ...
        -3/2 * growthStretchPrime(1) / growthStretch(1) + ...
        (3/80 * (growthStretchPrime(1) / growthStretch(1))^2 ...
        - 6/5 * growthStretchPrimePrime(1) / growthStretch(1)) ...
        .* (RMinusB + params.B) );

    %% Approximate viscous integrand near R = 0
    approxViscoIntegrand = -3 * ( ...
        ((growthStretch(1)^2) * dotgrowthStretchPrime(1) ...
        - growthStretch(1) * growthStretchPrime(1) * dgrowthStretchdt(1)) ...
        / growthStretch(1)^3 ...
        + (RMinusB + params.B) .* ...
        (13 * growthStretchPrime(1)^2 * dgrowthStretchdt(1) ...
        - 8 * growthStretch(1) * growthStretchPrimePrime(1) * dgrowthStretchdt(1) ...
        - 13 * growthStretch(1) * growthStretchPrime(1) * dotgrowthStretchPrime(1) ...
        + 8 * growthStretch(1)^2 * dotgrowthStretchPrimePrime(1)) ...
        / (10 * growthStretch(1)^3) );

    %% Composite integrands
    elasticIntegrandComposite = ...
        approxElasticIntegrand .* ...
        (RMinusB <= (params.radialStressIntegrandThreshold - params.B)) + ...
        elasticIntegrand .* ...
        (RMinusB >  (params.radialStressIntegrandThreshold - params.B));

    viscoIntegrandComposite = ...
        approxViscoIntegrand .* ...
        (RMinusB <= (params.radialStressIntegrandThreshold - params.B)) + ...
        viscoIntegrand .* ...
        (RMinusB >  (params.radialStressIntegrandThreshold - params.B));

    %% Integrate stresses
    elasticIntegral = cumtrapz(RMinusB, elasticIntegrandComposite);
    viscoIntegral   = cumtrapz(RMinusB, viscoIntegrandComposite);

    %% Radial stress (anchored at boundary)
    radialStress = ...
        mu .* (elasticIntegral - elasticIntegral(end)) + ...
        varsigma .* (viscoIntegral - viscoIntegral(end)) ...
        - params.kappa * (r(end) - params.B) / params.B;

    %% Viscoelastic stretch
    viscoelasticStretch = r ./ ((RMinusB + params.B) .* growthStretch);
    viscoelasticStretch(1) = 1;

    %% Taylor approximation near R = 0
    approxViscoElasticStretch = ...
        1 - (growthStretchPrime(1) / growthStretch(1)) .* ...
        (RMinusB + params.B) / 4;

    viscoelasticStretch = ...
        approxViscoElasticStretch .* ...
        (RMinusB <= (params.elasticStretchIntegrandThreshold - params.B)) + ...
        viscoelasticStretch .* ...
        (RMinusB >  (params.elasticStretchIntegrandThreshold - params.B));

    %% Hoop stress
    hoopStress = radialStress + ...
        mu .* (viscoelasticStretch.^2 - 1 ./ viscoelasticStretch.^4);

    %% Bulk stress
    bulkStress = radialStress + 2 * hoopStress;

end
